# Revising the Select Query I
Select * 
from CITY
where COUNTRYCODE = 'USA' AND POPULATION>100000;

# Revising the Select Query II
SELECT NAME
FROM CITY
WHERE COUNTRYCODE='USA' AND POPULATION>120000;

# Select All
SELECT *
FROM CITY;

# Select By ID
SELECT * 
FROM CITY
WHERE ID = 1661;

# Japanese Cities' Attributes
SELECT *
FROM CITY
WHERE COUNTRYCODE='JPN';

# Japanese Cities' Names
SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'JPN';

# Higher Than 75 Marks
SELECT NAME
FROM STUDENTS
WHERE MARKS>75
ORDER BY RIGHT(NAME, 3), ID;
 
# Employee Names
SELECT NAME
FROM EMPLOYEE
ORDER BY NAME;

# Employee Salaries
SELECT NAME
FROM EMPLOYEE
WHERE SALARY>2000 AND MONTHS<10
ORDER BY EMPLOYEE_ID;

# Weather Observation Station 1
SELECT CITY, STATE
FROM STATION;

# Weather Observation Station 3
SELECT DISTINCT CITY
FROM STATION
WHERE ID%2 = 0;

# Weather Observation Station 4
SELECT COUNT(*) - COUNT(DISTINCT CITY)
FROM STATION;

# Weather Observation Station 5
SELECT CITY, LENGTH(CITY) AS LEN
FROM STATION
ORDER BY LEN, CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) AS LEN
FROM STATION
GROUP BY CITY
ORDER BY LEN DESC LIMIT 1;

# Weather Observation Station 6
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%';

SELECT DISTINCT CITY 
FROM STATION
WHERE LEFT(CITY, 1) IN ('a','e','i','o','u');

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[a,e,i,o,u]';

# Weather Observation Station 7
SELECT DISTINCT CITY 
FROM STATION
WHERE RIGHT(CITY, 1) IN ('a','e','i','o','u');

# Weather Observation Station 8
SELECT DISTINCT CITY
FROM STATION
WHERE LEFT(CITY, 1) IN ('a','e','i','o','u') AND RIGHT(CITY, 1) IN ('a','e','i','o','u');

# Weather Observation Station 9
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^aeiou]';

# Weather Observation Station 10
SELECT DISTINCT CITY
FROM STATION 
WHERE RIGHT(CITY, 1) NOT IN ('a','e','i','o','u');

# Weather Observation Station 11
SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[^aeiou]|[^aeiou]$';

SELECT DISTINCT CITY 
FROM STATION
WHERE LEFT(CITY, 1) NOT IN ('a','e','i','o','u') 
OR RIGHT(CITY, 1) NOT IN ('a','e','i','o','u');

# Weather Observation Station 12
SELECT DISTINCT CITY 
FROM STATION 
WHERE CITY REGEXP '^[^aeiou].*[^aeiou]$';

SELECT DISTINCT CITY
FROM STATION
WHERE LEFT(CITY, 1) NOT IN ('a','e','i','o','u')
AND RIGHT(CITY, 1) NOT IN ('a','e','i','o','u');

